from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
import pandas as pd
import os
from datetime import datetime

EXPORT_DIR = "exports"
os.makedirs(EXPORT_DIR, exist_ok=True)

def export_to_docx(title: str, data: list) -> str:
    """Export to Word document."""
    doc = Document()
    
    # Header
    heading = doc.add_heading(title, 0)
    heading.alignment = WD_ALIGN_PARAGRAPH.CENTER
    doc.add_paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    doc.add_paragraph(f"Total Questions: {len(data)}")
    doc.add_paragraph()
    
    # Summary
    answered = len([d for d in data if not d.get('not_found_in_refs', False)])
    doc.add_heading("Summary", level=1)
    doc.add_paragraph(f"Questions Answered: {answered}/{len(data)}")
    doc.add_paragraph(f"With Citations: {len([d for d in data if d.get('citations')])}")
    doc.add_paragraph()
    
    # Responses
    doc.add_heading("Detailed Responses", level=1)
    
    for item in data:
        # Question
        q_para = doc.add_paragraph()
        q_run = q_para.add_run(f"Q{item['question_number']}: {item['question_text']}")
        q_run.bold = True
        
        # Answer
        a_para = doc.add_paragraph()
        if item.get('edited_by_user'):
            a_para.add_run("Answer (Edited): ").italic = True
        else:
            a_para.add_run("Answer: ").italic = True
        
        answer_text = item.get('final_answer') or item.get('generated_answer') or "Not found in references."
        
        if answer_text == "Not found in references." or item.get('not_found_in_refs'):
            a_run = a_para.add_run(answer_text)
            a_run.font.color.rgb = RGBColor(255, 0, 0)
            a_run.italic = True
        else:
            a_para.add_run(answer_text)
        
        # Citations
        if item.get('citations'):
            c_para = doc.add_paragraph()
            c_para.add_run("Sources: ").italic = True
            c_para.add_run("; ".join([
                f"{c['document_name']} (p.{c['page_number']})"
                for c in item['citations']
            ]))
            c_para.runs[-1].font.size = Pt(9)
            c_para.runs[-1].font.color.rgb = RGBColor(100, 100, 100)
        
        doc.add_paragraph()
    
    # Footer
    doc.add_paragraph()
    footer = doc.add_paragraph("Generated by Questionnaire AI System")
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer.runs[0].font.size = Pt(8)
    footer.runs[0].font.color.rgb = RGBColor(128, 128, 128)
    
    filename = f"{EXPORT_DIR}/{title.replace(' ', '_')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.docx"
    doc.save(filename)
    return filename

def export_to_excel(title: str, data: list) -> str:
    """Export to Excel."""
    rows = []
    for item in data:
        rows.append({
            "Question #": item['question_number'],
            "Question": item['question_text'],
            "Answer": item.get('final_answer') or item.get('generated_answer') or "Not found in references.",
            "Citations": "; ".join([
                f"{c['document_name']} p.{c['page_number']}"
                for c in item.get('citations', [])
            ]),
            "Edited by User": "Yes" if item.get('edited_by_user') else "No"
        })
    
    df = pd.DataFrame(rows)
    filename = f"{EXPORT_DIR}/{title.replace(' ', '_')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.xlsx"
    df.to_excel(filename, index=False, sheet_name='Responses')
    return filename